controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position:
      type: forward_command_controller/ForwardCommandController

    position_trajectory:
      type: joint_trajectory_controller/JointTrajectoryController

position:
  ros__parameters:
    joints:
      - horizontal_joint
      - vertical_joint
      - insertion_joint
    interface_name: position


position_trajectory:
  ros__parameters:
    joints:
      - horizontal_joint
      - vertical_joint
      - insertion_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 10.0
    action_monitor_rate: 10.0

    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)